[versions]
kotlin = "2.2.10"
dokka = "2.0.0"
springBoot = "3.5.5"
vaadin-base = "24.8.6"
kotlinPoet = "2.2.0"
testContainers = "1.21.3"
jooq = "3.19.10"
karibu = "2.3.0"

[libraries]
spring-boot-bom = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "springBoot" }
vaadin-base-bom = { module = "com.vaadin:vaadin-bom", version.ref = "vaadin-base" }
kotlinPoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinPoet" }
ektorp = "org.ektorp:org.ektorp.spring:1.5.0"
acraJava = "ch.acra:acra-javacore:5.8.4"
orgJson = "org.codeartisans:org.json:20161124"
commonsText = "org.apache.commons:commons-text:1.13.1"
xbibTime = "org.xbib:time:2.3.0"
retrace = "com.faendir.proguard:retrace:1.3"
fuzzywuzzy = "me.xdrop:fuzzywuzzy:1.4.0"
ziplet = "com.faendir.ziplet:ziplet:2.5.2"
univocityParser = "com.univocity:univocity-parsers:2.9.1"
avatarGenerator = "com.talanlabs:avatar-generator:1.1.0"
apexCharts = "com.github.appreciated:apexcharts:24.0.2"
vaadin-paperMenuButton = "com.github.appreciated:vaadin-paper-menu-button:2.0.2"
kotlin-coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2"
kotlin-logging = "io.github.microutils:kotlin-logging-jvm:3.0.5"
spring-mockk = "com.ninja-squad:springmockk:4.0.2"
strikt = "io.strikt:strikt-core:0.35.1"
springdoc = "org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.13"
guava = "com.google.guava:guava:33.4.8-jre"
testContainers-mysql = { module = "org.testcontainers:mysql", version.ref = "testContainers" }
testContainers-junit = { module = "org.testcontainers:junit-jupiter", version.ref = "testContainers" }
karibu-testing = { module = "com.github.mvysny.kaributesting:karibu-testing-v24", version.ref = "karibu" }
karibu-spring = { module = "com.github.mvysny.kaributesting:karibu-testing-v10-spring", version.ref = "karibu" }

[plugins]
jooq = { id = "nu.studer.jooq", version = "9.0" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
jgitver = { id = "fr.brouillard.oss.gradle.jgitver", version = "0.10.0-rc03" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-noarg = { id = "org.jetbrains.kotlin.plugin.noarg", version.ref = "kotlin" }
springBoot = { id = "org.springframework.boot", version.ref = "springBoot" }
vaadin = { id = "com.vaadin", version.ref = "vaadin-base" }
spotless = { id = "com.diffplug.spotless", version = "7.0.4" }
