[versions]
kotlin = "1.7.20"
dokka = "1.7.20"
jgitver = "0.10.0-rc03"
nexusPublish = "1.1.0"
spring-boot = "2.7.5"
vaadin-flow = "23.2.6"
kotlinPoet = "1.12.0"
docker-gradle = "0.34.0"
autoService = "1.0.1"

[libraries]
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-allopen = { module = "org.jetbrains.kotlin:kotlin-allopen", version.ref = "kotlin" }
kotlin-noarg = { module = "org.jetbrains.kotlin:kotlin-noarg", version.ref = "kotlin" }
dokka-gradle = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
dokka-core = { module = "org.jetbrains.dokka:dokka-core", version.ref = "dokka" }
jgitver = { module = "gradle.plugin.fr.brouillard.oss.gradle:gradle-jgitver-plugin", version.ref = "jgitver" }
nexusPublish = { module = "io.github.gradle-nexus:publish-plugin", version.ref = "nexusPublish" }
spring-boot-gradle = { module = "org.springframework.boot:spring-boot-gradle-plugin", version.ref = "spring-boot" }
spring-boot-bom = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
vaadin-flow-gradle = { module = "com.vaadin:vaadin-gradle-plugin", version.ref = "vaadin-flow" }
vaadin-flow-bom = { module = "com.vaadin:vaadin-bom", version.ref = "vaadin-flow" }
kotlinPoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinPoet" }
docker-gradle = { module = "com.palantir.gradle.docker:gradle-docker", version.ref = "docker-gradle" }
autoService-processor = { module = "com.google.auto.service:auto-service", version.ref = "autoService" }
autoService-annotations = { module = "com.google.auto.service:auto-service", version.ref = "autoService" }
liquibaseKotlinDsl = "com.faendir.liquibase:liquibase-kotlin-dsl:3.1.0"
ektorp = "org.ektorp:org.ektorp.spring:1.5.0"
acraJava = "ch.acra:acra-javacore:5.8.4"
orgJson = "org.codeartisans:org.json:20161124"
commonsText = "org.apache.commons:commons-text:1.10.0"
xbibTime = "org.xbib:time:2.3.0"
retrace = "com.faendir.proguard:retrace:1.3"
fuzzywuzzy = "me.xdrop:fuzzywuzzy:1.4.0"
ziplet = "com.faendir.ziplet:ziplet:2.4.3"
univocityParser = "com.univocity:univocity-parsers:2.9.1"
avatarGenerator = "com.talanlabs:avatar-generator:1.1.0"
apexCharts = "com.github.appreciated:apexcharts:23.0.0"
gridLayout = "com.github.appreciated:vaadin-css-grid:2.0.0"
vaadin-paperMenuButton = "com.github.appreciated:vaadin-paper-menu-button:2.0.2"
kotlin-coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4"
kotlin-logging = "io.github.microutils:kotlin-logging-jvm:3.0.2"
spring-mockk = "com.ninja-squad:springmockk:3.1.1"
strikt = "io.strikt:strikt-core:0.34.1"
mariadb4j = "org.craftercms.mariaDB4j:mariaDB4j-springboot:2.5.3"
mariadbClient = "org.mariadb.jdbc:mariadb-java-client:3.0.8"
springdoc = "org.springdoc:springdoc-openapi-ui:1.6.12"
